"""Metadata de presentación de cada KPI: etiqueta, fórmula y explicación
sencilla (tooltips). Fuente única para el frontend vía API."""

KPI_META = {
    "roic": {
        "label": "ROIC",
        "formula": "NOPAT / capital invertido promedio; NOPAT = EBIT × (1 − tasa efectiva)",
        "explain": "Cuánta rentabilidad genera la empresa por cada sol invertido en el negocio (deuda + patrimonio − caja). Es el mejor indicador de calidad del negocio.",
    },
    "roe": {
        "label": "ROE",
        "formula": "Utilidad neta atribuible / patrimonio atribuible promedio",
        "explain": "Rentabilidad sobre el dinero de los accionistas.",
    },
    "roa": {
        "label": "ROA",
        "formula": "Utilidad neta / activos totales promedio",
        "explain": "Qué tan eficientemente los activos generan utilidades.",
    },
    "gross_margin": {
        "label": "Margen bruto",
        "formula": "Utilidad bruta / ingresos",
        "explain": "Porcentaje de las ventas que queda después del costo directo de producir.",
    },
    "operating_margin": {
        "label": "Margen operativo",
        "formula": "Utilidad operativa / ingresos",
        "explain": "Porcentaje de las ventas que queda después de todos los costos del negocio (antes de intereses e impuestos).",
    },
    "net_margin": {
        "label": "Margen neto",
        "formula": "Utilidad neta atribuible / ingresos",
        "explain": "Porcentaje de las ventas que se convierte en utilidad final para los accionistas.",
    },
    "revenue_growth_yoy": {
        "label": "Crecimiento de ingresos",
        "formula": "(Ingresos actuales − ingresos mismo semestre año anterior) / ingresos año anterior",
        "explain": "Cuánto crecieron las ventas frente al mismo semestre del año pasado.",
    },
    "operating_income_growth_yoy": {
        "label": "Crecimiento utilidad operativa",
        "formula": "Variación interanual de la utilidad operativa (mismo semestre)",
        "explain": "Cuánto creció la ganancia del negocio principal.",
    },
    "net_income_growth_yoy": {
        "label": "Crecimiento utilidad neta",
        "formula": "Variación interanual de la utilidad neta (mismo semestre)",
        "explain": "Cuánto creció la utilidad final.",
    },
    "total_assets_growth_yoy": {
        "label": "Crecimiento de activos",
        "formula": "Variación interanual de los activos totales",
        "explain": "Ritmo de expansión del balance.",
    },
    "equity_growth_yoy": {
        "label": "Crecimiento del patrimonio",
        "formula": "Variación interanual del patrimonio total",
        "explain": "Cuánto crece el valor contable de la empresa.",
    },
    "operating_cash_flow_growth_yoy": {
        "label": "Crecimiento del flujo operativo",
        "formula": "Variación interanual del flujo de caja operativo",
        "explain": "Cuánto crece la caja que genera la operación.",
    },
    "fcf_growth_yoy": {
        "label": "Crecimiento del FCF",
        "formula": "Variación interanual del flujo de caja libre",
        "explain": "Cuánto crece la caja disponible después de inversiones.",
    },
    "revenue_cagr_3y": {"label": "CAGR ingresos 3a", "formula": "(Ingresos finales / iniciales)^(1/3) − 1",
                        "explain": "Crecimiento anual compuesto de ventas en 3 años."},
    "net_income_cagr_3y": {"label": "CAGR utilidad 3a", "formula": "(Utilidad final / inicial)^(1/3) − 1",
                           "explain": "Crecimiento anual compuesto de la utilidad en 3 años."},
    "fcf_cagr_3y": {"label": "CAGR FCF 3a", "formula": "(FCF final / inicial)^(1/3) − 1",
                    "explain": "Crecimiento anual compuesto del flujo de caja libre en 3 años."},
    "free_cash_flow": {
        "label": "Flujo de caja libre",
        "formula": "Flujo de caja operativo − CAPEX",
        "explain": "Caja que queda después de mantener y expandir el negocio; es lo que realmente puede repartirse o reinvertirse.",
    },
    "fcf_margin": {
        "label": "Margen FCF",
        "formula": "Flujo de caja libre / ingresos",
        "explain": "Porcentaje de las ventas que se convierte en caja disponible.",
    },
    "cash_conversion": {
        "label": "Conversión de caja",
        "formula": "Flujo de caja operativo / utilidad neta",
        "explain": "Qué proporción de la utilidad contable se convierte en efectivo real. Cerca de 1 o más es saludable.",
    },
    "dividend_coverage": {
        "label": "Cobertura del dividendo",
        "formula": "Flujo de caja libre / dividendos pagados",
        "explain": "Cuántas veces el FCF cubre los dividendos. Menor a 1 indica dividendos financiados con deuda o caja.",
    },
    "total_debt": {"label": "Deuda total", "formula": "Deuda corto plazo + deuda largo plazo",
                   "explain": "Obligaciones financieras totales."},
    "net_debt": {"label": "Deuda neta", "formula": "Deuda total − efectivo y equivalentes",
                 "explain": "Deuda que quedaría después de usar toda la caja. Puede ser negativa (más caja que deuda)."},
    "debt_to_equity": {"label": "Deuda financiera / Patrimonio", "formula": "Deuda financiera (corto + largo plazo) / patrimonio total",
                       "explain": "Cuánta deuda financiera hay por cada sol de patrimonio."},
    "liabilities_to_equity": {"label": "Pasivo / Patrimonio (apalancamiento)", "formula": "Pasivo total / patrimonio total",
                              "explain": "Apalancamiento total: todos los pasivos por cada sol de patrimonio. Es el indicador que la BVL/SMV reporta como 'Deuda/Patrimonio'."},
    "debt_to_assets": {"label": "Deuda / Activos", "formula": "Deuda total / activos totales",
                       "explain": "Proporción de los activos financiada con deuda."},
    "ebitda": {"label": "EBITDA", "formula": "EBIT + depreciación y amortización (aproximado)",
               "explain": "Ganancia operativa antes de cargos contables sin salida de caja."},
    "net_debt_to_ebitda": {
        "label": "Deuda neta / EBITDA",
        "formula": "Deuda neta / EBITDA anualizado",
        "explain": "Años de EBITDA necesarios para pagar la deuda neta. Menos de 1.5 es cómodo; más de 3 es arriesgado.",
    },
    "interest_coverage": {
        "label": "Cobertura de intereses",
        "formula": "EBIT / gastos financieros",
        "explain": "Cuántas veces la ganancia operativa cubre el pago de intereses. Más de 5 es holgado.",
    },
    "current_ratio": {
        "label": "Ratio corriente",
        "formula": "Activos corrientes / pasivos corrientes",
        "explain": "Capacidad de pagar obligaciones de corto plazo. Entre 1.2 y 2.5 es saludable.",
    },
    "quick_ratio": {"label": "Prueba ácida", "formula": "(Activos corrientes − inventarios) / pasivos corrientes",
                    "explain": "Liquidez inmediata sin depender de vender inventario."},
    "working_capital": {"label": "Capital de trabajo", "formula": "Activos corrientes − pasivos corrientes",
                        "explain": "Colchón de recursos para operar el día a día."},
    "asset_turnover": {"label": "Rotación de activos", "formula": "Ingresos / activos totales promedio",
                       "explain": "Ventas generadas por cada sol de activos."},
    "days_sales_outstanding": {"label": "Días de cobranza", "formula": "Cuentas por cobrar promedio / ingresos × días del periodo",
                               "explain": "Días que tarda la empresa en cobrar sus ventas."},
    "days_inventory": {"label": "Días de inventario", "formula": "Inventario promedio / costo de ventas × días del periodo",
                       "explain": "Días que el inventario permanece almacenado."},
    "equity_to_assets": {"label": "Patrimonio / Activos", "formula": "Patrimonio total / activos totales",
                         "explain": "Solidez patrimonial: proporción del balance financiada con capital propio."},
    "revenue": {"label": "Ingresos", "formula": "Ingresos de actividades ordinarias", "explain": "Ventas del periodo."},
    "operating_income": {"label": "Utilidad operativa", "formula": "Resultado de la operación", "explain": "Ganancia del negocio principal."},
    "net_income": {"label": "Utilidad neta", "formula": "Resultado neto del ejercicio", "explain": "Ganancia final del periodo."},
    "operating_cash_flow": {"label": "Flujo operativo", "formula": "Flujo de efectivo de actividades de operación", "explain": "Caja generada por la operación."},
}

KPI_SECTIONS = {
    "Rentabilidad": ["roic", "roe", "roa", "gross_margin", "operating_margin", "net_margin"],
    "Crecimiento": ["revenue_growth_yoy", "operating_income_growth_yoy", "net_income_growth_yoy",
                    "total_assets_growth_yoy", "equity_growth_yoy", "operating_cash_flow_growth_yoy",
                    "fcf_growth_yoy", "revenue_cagr_3y", "net_income_cagr_3y", "fcf_cagr_3y"],
    "Flujo de caja": ["free_cash_flow", "fcf_margin", "cash_conversion", "dividend_coverage"],
    "Endeudamiento": ["total_debt", "net_debt", "debt_to_equity", "liabilities_to_equity",
                      "debt_to_assets", "ebitda", "net_debt_to_ebitda", "interest_coverage"],
    "Liquidez": ["current_ratio", "quick_ratio", "working_capital"],
    "Eficiencia": ["asset_turnover", "days_sales_outstanding", "days_inventory", "equity_to_assets"],
}
